server:
  port: 9101
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    non-secure-port: 80
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
