server:
  port: 9092
details:
  quotesService: QUOTES-SERVICE
  companiesService: COMPANIES-SERVICE
ribbon:
  IsSecure: false
  eureka:
    approximateZoneFromHostname: true
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    non-secure-port: 80
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
